import Link from "next/link";
import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { getServerSupabase } from "@/lib/supabase-server";
import {
  ARTIFACT_ORDER,
  ARTIFACT_SLUGS,
  type Customer,
  type Run,
} from "@/lib/types";

// Server Component. react-markdown renders fine on the server; M6 will
// extract a client wrapper if/when the annotation overlay needs one.
//
// No rehype-raw — markdown is generated by /base-agent and is trusted to be
// well-formed but should not be allowed to inject raw HTML.

export default async function ArtifactPage({
  params,
}: {
  params: Promise<{ slug: string; artifact: string }>;
}) {
  const { slug, artifact } = await params;

  // Allowlist gate: anything outside the 6-slot order 404s without a query.
  // `scraped-pages` is intentionally excluded — it has bespoke handling
  // deferred to a later milestone.
  if (!ARTIFACT_SLUGS.has(artifact)) {
    notFound();
  }

  const supabase = await getServerSupabase();

  const { data: customerRow, error: customerError } = await supabase
    .from("customers")
    .select("id, slug, name, created_at")
    .eq("slug", slug)
    .maybeSingle();

  if (customerError) {
    throw new Error(`Failed to load customer: ${customerError.message}`);
  }
  if (!customerRow) {
    notFound();
  }
  const customer = customerRow as Customer;

  // Narrow select: state isn't read on this page (see M4 review note).
  const { data: runRow, error: runError } = await supabase
    .from("runs")
    .select("id, customer_id, started_at, stage_complete")
    .eq("customer_id", customer.id)
    .order("started_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (runError) {
    throw new Error(`Failed to load latest run: ${runError.message}`);
  }
  if (!runRow) {
    notFound();
  }
  const run = runRow as Pick<Run, "id" | "customer_id" | "started_at" | "stage_complete">;

  // Fetch the requested artifact's content + the full artifact roster (for
  // footer iteration) in parallel — both share `run_id` and don't depend on
  // each other.
  const [artifactRes, rosterRes] = await Promise.all([
    supabase
      .from("artifacts")
      .select("artifact_name, content")
      .eq("run_id", run.id)
      .eq("artifact_name", artifact)
      .maybeSingle(),
    supabase
      .from("artifacts")
      .select("artifact_name")
      .eq("run_id", run.id),
  ]);

  if (artifactRes.error) {
    throw new Error(`Failed to load artifact: ${artifactRes.error.message}`);
  }
  if (!artifactRes.data) {
    notFound();
  }
  const content = artifactRes.data.content as string;

  if (rosterRes.error) {
    throw new Error(`Failed to load artifact roster: ${rosterRes.error.message}`);
  }
  const presentNames = new Set<string>(
    (rosterRes.data ?? []).map((r) => r.artifact_name as string),
  );

  // Find the current chapter via name lookup (allowlist guarantees it exists).
  const currentChapter = ARTIFACT_ORDER.find((c) => c.artifact === artifact);
  if (!currentChapter) notFound(); // unreachable given allowlist; satisfies TS.
  const currentIndex = ARTIFACT_ORDER.indexOf(currentChapter);

  // Footer semantics: link to the next chapter that ACTUALLY has an artifact
  // row, not the next slot in ARTIFACT_ORDER. So if a customer has only
  // brain-doc + discovery-prompt (system-prompt missing), brain-doc's footer
  // points at discovery-prompt rather than dead-linking to a 404.
  const nextChapter =
    ARTIFACT_ORDER.slice(currentIndex + 1).find((c) =>
      presentNames.has(c.artifact),
    ) ?? null;

  return (
    <main className="min-h-screen p-12 bg-[#FAFAF7] text-[#1A1A1A]">
      {/* Top bar */}
      <div className="max-w-3xl mx-auto text-sm text-[#6B6B6B]">
        <Link
          href={`/c/${customer.slug}`}
          className="hover:text-[#1A1A1A] transition-colors"
        >
          ← {customer.name}
        </Link>
        <span className="mx-2 text-[#C0C0BA]">·</span>
        <span>{currentChapter.name}</span>
      </div>

      {/* Body */}
      <article className="max-w-3xl mx-auto mt-10 prose prose-stone font-serif">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
      </article>

      {/* Footer: only when a later chapter exists with an artifact row */}
      {nextChapter ? (
        <div className="max-w-3xl mx-auto mt-16 text-sm">
          <Link
            href={`/c/${customer.slug}/${nextChapter.artifact}`}
            className="text-[#6B6B6B] hover:text-[#1A1A1A] transition-colors"
          >
            Next: {nextChapter.name} →
          </Link>
        </div>
      ) : null}
    </main>
  );
}
